### ISSUE TITLE
How to clear input value in DayPickerInput

### ISSUE THREAD

**Issue by kunchit** [gpbl/react-day-picker#1005]
I have code example like this :
https://codesandbox.io/s/quizzical-river-278v1

when I click reset the value in DayPickerInput is not clear

**Comment by HARIKSREEE** [comment]
Hi Kunchit,
I am using Day Picker instead of DayPickerInput. If we use a normal input along with react day picker, we will get lot of flexibility in handling the functionality. But need to write bit more lines of code.
Again it completely depends on people on whether they need to use DayPicker or DayPickerInput.
I personally like DayPicker alone
With our custom function we can have a great day picker.. :)

**Comment by jotielim** [comment]
This is a bug in v7.4.0. See https://github.com/gpbl/react-day-picker/pull/990

**Comment by gpbl** [comment]
Fixed in v7.4.1: https://codesandbox.io/s/magical-darkness-kybqr?file=/src/App.js

**Comment by pigpudle** [comment]
@gpbl it doesn't work in your codesandbox. Clicking on 'Reset Search' button with invalid date entered have no effect on input value.

![image](https://user-images.githubusercontent.com/91419045/154806429-225a0f6b-c7e4-4ded-9cc7-fb2cded43762.png)
