### ISSUE TITLE
Can't resolve 'react-day-picker/DayPicker' in v7.4.4

### ISSUE THREAD

**Issue by TheFrogPrince** [gpbl/react-day-picker#1018]
**Describe the bug**
Build started blowing with:  Module not found: Error: Can't resolve 'react-day-picker/DayPicker' in 

**To Reproduce**
Clone [this CodeSandbox](https://codesandbox.io/s/XDAE3x0W8) to reproduce the bug.

**Expected behavior**
Not expecting this error.

**Screenshots**

**Additional context**
Major version # should be updated for changes that are not backwards compatible.
https://docs.npmjs.com/about-semantic-versioning

**Comment by TheFrogPrince** [comment]
If I lock in version 7.4.1, my builds start working again, but I do so hate locking in specific versions.

**Comment by gpbl** [comment]
It comes unexpected to me seeing people are importing `DayPicker` that way — which has never been supported or suggested anywhere — why can’t you import the component as the per docs?

**Comment by gpbl** [comment]
Also @shlomitc is reporting this issue: https://github.com/gpbl/react-day-picker/issues/1017
Could you please clarify what is the reason of this kind of import?

**Comment by shlomitc** [comment]
@gpbl we've been using `react-day-picker` in [our project](https://github.com/wix/wix-style-react) since January 18, starting from version 7.0.7.

Hard to say what was the reason back then, maybe this seemed like a consistent way to import the `DayPicker` component, the same way you import the `DayPickerInput`(`import DayPickerInput from 'react-day-picker/DayPickerInput'`)

I looked thoroughly in the history docs and you're right, it doesn't look like this was the recommended way to import, so I guess this comes as a mistake from our side.

Anyway, thanks for the speedy responses.

**Comment by gpbl** [comment]
Thanks @shlomitc no worries - the API is indeed confusing. It is easy to add it again, if this is affecting many people...

**Comment by gpbl** [comment]
I've published an update that should fix that import !
