### ISSUE TITLE
Support for dates below 1970?

### ISSUE THREAD

**Issue by vinayakpatil** [gpbl/react-day-picker#118]

**Comment by gpbl** [comment]
Hi @vinayakpatil what are your problems with dates before 1970?

**Comment by vinayakpatil** [comment]
@gpbl I have to render a date range from `0001-01-01` to `9990-01-01`. I am using ISO 8601 format here `yyyy-mm-dd` in order to use dates below 1970. Once I select a day from the calendar from year `0 to 100`, 1900 is padded automatically.

**Comment by gpbl** [comment]
This a use case I never tested. So is the problem related to dates before 1970 or before 100? 

I think the "usual" issues with standard Date objects also apply for the calendar, since it works with Date objects. Try googling a bit, e.g. I've found [this article](http://scholarslab.org/research-and-development/parsing-bc-dates-with-javascript) that could be useful to clear things up.

**Comment by gpbl** [comment]
I'm closing this since no answer from @vinayakpatil :)
