### ISSUE TITLE
React 15

### ISSUE THREAD

**Issue by psvitz** [gpbl/react-day-picker#166]
Hi,

I had this component working fine while I was using React 14. I just updated React and now it looks like this component is no longer rendering.

versions:
    "react": "^15.0.2",,
    "react-day-picker": "^1.3.2",
    "react-dom": "^15.0.2",
    "browserify": "^11.0.1",

When I load a page that contains this component I get a number of errors, I suspect the most telling is a warning complaining that React.createElement got a null.

I am **not** using ES2015.

**Comment by gpbl** [comment]
Hi @psvitz this is related to the internal upgrade to Babel 6 with the v1.3.1: https://github.com/gpbl/react-day-picker/issues/136

Could you upgrade to v2 to see if this problem is solved? (Please read the [changelog](https://github.com/gpbl/react-day-picker/blob/master/CHANGELOG.md) first as there are some small breaking changes)

**Comment by psvitz** [comment]
Thanks @gpbl! This resolved my issue.
