### ISSUE TITLE
Add an example using tailwind

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#1720]
Some developers [are wondering](https://github.com/gpbl/react-day-picker/discussions/1392#discussioncomment-4056576) how to use [tailwindcss](http://tailwindcss.com) with DayPicker.

@malcolm-kee proposed a solution here:

Repo: https://github.com/malcolm-kee/react-day-picker-tailwind
Demo: https://react-day-picker-tailwind.netlify.app/

but we could add it to the documentation.

**Comment by ialexanderbrito** [comment]
Thanks examples

**Comment by vixeven** [comment]
@shadcn's [UI](https://ui.shadcn.com/) components library also uses `react-day-picker`:

https://ui.shadcn.com/docs/components/calendar

**Comment by tyeetale** [comment]
I would also love to get the caption_layout version because the above examples only show the nav buttons but do not select month and year. For whatever reason, I've been struggling with disabling the aria-hidden="true" divs within the calendar forked from shadcn.

![Screenshot 2023-11-14 at 16 06 24](https://github.com/gpbl/react-day-picker/assets/17817587/2f58bf91-0a24-4a3b-b2fe-ffa99e8a4700)
<img width="887" alt="Screenshot 2023-11-14 at 16 06 50" src="https://github.com/gpbl/react-day-picker/assets/17817587/7aac2a26-cf9a-4aa7-926f-5e2f5160d35a">

**Comment by tyeetale** [comment]
Actually nevermind. Again it was a tailwind issue on creating caption labels. 
<img width="887" alt="Screenshot 2023-11-14 at 16 19 32" src="https://github.com/gpbl/react-day-picker/assets/17817587/7a0b1d57-098b-4543-8ea5-e7cd3b8558e4">

**Comment by gpbl** [comment]
Closing this as DayPicker 9 is in beta and comes up with a simplified HTML tree and UI elements: the changes will allow an easier and solid customization via TailwindCSS. 

See the example here:
https://react-day-picker.js.org/next/using-daypicker/styling#tailwind-css

[Try the beta](http://react-day-picker.js.org/next/start) and let me know if it works for you - and if not! Thanks.
