### ISSUE TITLE
Bug: captionLayout has no effect

### ISSUE THREAD

**Issue by dancherb** [gpbl/react-day-picker#1930]
```
import 'react-day-picker/dist/style.css';
import { DayPicker } from 'react-day-picker';

export default function Calendar() {
    return (
        <DayPicker
            captionLayout="dropdown"
        />
    )
}
```

This is immediately visible on the [CodeSandbox](https://codesandbox.io/s/react-day-picker-8-vl4ry?file=/src/App.tsx) - just add `captionLayout="dropdown"`. The navigation does not change.

    "next": "^13.4.19",
    "react-day-picker": "^8.8.2",

**Comment by gpbl** [comment]
Hi @dancherb, since we cannot render drop-downs that load an infinite numbers of years, you need to limit the month navigation to make it work:

https://react-day-picker.js.org/basics/navigation#choosing-a-caption-layout

Thanks for this feedback - this should be forced by typings in the next version of DayPicker.
