### ISSUE TITLE
Custom callback with setState in onMonthChange event.

### ISSUE THREAD

**Issue by ifedko** [gpbl/react-day-picker#210]
I have a case with disabled days when available days is loaded from backend for every month changing.
All loaded available days should be stored in state.
I tried to use onMonthChange event. But onMonthChange handler is using in setState's callback.
So state is updated, but month is not switched.

Does anyone know how to resolve this issue?

Code example:

```jsx
<DatePicker
  ref={c => this.calendar = c}
  initialMonth={date.toDate()}
  onMonthChange={this.handleMonthChange.bind(this)}
  disabledDays={this.isDisabledDay}
/>
```

where

```js
isDisabledDay(day) {
  return this.state.availableDates.find((availableDate) => {
    return moment(day).format('YYYY-MM-DD') === moment(availableDate).format('YYYY-MM-DD');
  }) === undefined;
}
```

and

```js
handleMonthChange(date) {
        const dates = this.props.api.getAvailableDates(`/`);
        this.setState({availableDates: dates});
    }
```

**Comment by gpbl** [comment]
Hi @ifedko, what do you mean when you say the month is not switched? Doesn't the calendar display the next/previous month?

**Comment by ifedko** [comment]
Hi @gpbl, yes, calendar doesn't display the next/previous months.

**Comment by gpbl** [comment]
... and if you remove the `onMonthChange` prop, do the months change?

**Comment by ifedko** [comment]
Yes, months change. And if remove `this.setState({availableDates: dates});` from`onMonthChange`months change.

**Comment by ifedko** [comment]
IMO the issue is in setState in setState callback.

**Comment by gpbl** [comment]
@ifedko 

> IMO the issue is in setState in setState callback.

Do you mean the call to `this.props.onMonthChange` [here](https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L168-L170)? Maybe there's a rendering chain not working as I was expecting...

I'd like to debug your issue better – could you can fork the repo to add an example showing the problem? See http://www.gpbl.org/react-day-picker/Examples.html 

Otherwise you need to wait I find some free time first 😃

**Comment by ifedko** [comment]
> Do you mean the call to this.props.onMonthChange here? Maybe there's a rendering chain not working as I was expecting...

Yes, that's right.

@gpbl I will try to add an example showing the issue.

**Comment by ifedko** [comment]
Hi @gpbl
I've added example in my fork https://github.com/ifedko/react-day-picker/commit/9c2dbff80d50001173a518d908daeb8c51e783cb
Case with issue:
1. Show calendar (without setting selected day)
2. Try to change month.

If remove ```initMonth={(this.state.selectedDay || new Date())}``` prop of DayPicker and it works as well. But in some cases I need to init month from Redux state.

If set ```initMonth={this.state.selectedDay}``` there is an error "DateUtils.js:9 Uncaught TypeError: Cannot read property 'getTime' of null" in DateUtils.

Could you check the case?

**Comment by ifedko** [comment]
@gpbl this fix https://github.com/ifedko/react-day-picker/commit/7c5825cd3391816bd7fe98aca04eb214f3696c67 fixed my problem.

**Comment by ifedko** [comment]
Hi @gpbl
Do you have any time to check out my fix?

**Comment by gpbl** [comment]
Hi @ifedko,

I am a bit confused by your fix as it doesn't seem related to what we were talking about before :)

> If remove initMonth={(this.state.selectedDay || new Date())} prop of DayPicker and it works as well. But in some cases I need to init month from Redux state.

I don't understand what do you mean with the above. If you have the `selectedDay` from a redux store, I guess you are passing it as prop to the component (using `connect()`). 

If is this the case, you just need to initialize the state of your component using the passed prop. Doing this way, your `state.selectedDay` will have the value found in your store. E.g. in a component class:

```js
class MyComponentToSelectDates extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
             selectedDay: props.selectedDay
        }
    }
       /* snip */
}
// here redux connect to pass selectedDay as prop
```

or if I guessing your existing code correctly, you could just write:

```jsx
<DayPicker initialMonth={ this.state.selectedDay || this.props.selectedDay || new Date() } />
````

> If set initMonth={this.state.selectedDay} there is an error "DateUtils.js:9 Uncaught TypeError: Cannot read property 'getTime' of null" in DateUtils.

Yes, because you can't pass a `null` value to the `initialMonth` prop. It requires a valid date. If you get this error, it is because `selectedDay` has a null value, thing that you should avoid with the solution above.

**Comment by ifedko** [comment]
@gpbl thanks for detailed answer! I understand what you are talking about.

But I have a use case when selectedDay is empty by default.
User sees form with datepicker and can choose date changing months without selected day by default. It's not correct to show default date in some cases. 
What do you think about this case?

**Comment by ifedko** [comment]
@gpbl I've found solution. I won't use initialMonth property if selectedDay is null.

I can change my example if it's usefull.

**Comment by gpbl** [comment]
I believe the problem is treating an *empty* value as `null`: if you set `selectedDay` to `undefined` it should fallback to the default prop, hence or you keep `selectedDay` as `undefined` when not set, or if you need it as `null` you can write 

```jsx
<DayPicker initialMonth={ this.state.selectedDay || undefined } />
```

which is the same actually as

```jsx
<DayPicker initialMonth={ this.state.selectedDay || new Date() }
```

> I can change my example if it's usefull.

Yup I'm curious to see as you solved this :)

**Comment by ifedko** [comment]
Hi @gpbl 
I used your way (it's better than mine:) ):

```<DayPicker initialMonth={ this.state.selectedDay || undefined } />```

Thanks a lot!

So after the commit
https://github.com/ifedko/react-day-picker/commit/967b37ded897090fb10c5cbe32934befa085f97a
there is completely example Input Field with overlay and DisabledDays.

Do you want to include this example?

**Comment by gpbl** [comment]
Awesome! I wouldn't include it since that example is already too complex (I hope to add a component for showing the calendar in an overlay, see #213). Maybe I could add an example showing how to fetch data when switching the month, tough...
