### ISSUE TITLE
Using state variable for startMonth doesn't update the day picker

### ISSUE THREAD

**Issue by the-marolie** [gpbl/react-day-picker#2337]
If we use a state variable for startMonth, the day picker doesn't update the initial month

## Code 

```tsx
import { DayPicker } from 'react-day-picker';
import {useState, useEffect} from  'react';
import 'react-day-picker/dist/style.css';
import "./styles.css";

export default function App() {
  const [startMonth, setStartMonth] = useState('');

  useEffect(() => {
    setStartMonth(new Date(2024,2));
  }, [])

  return (
    <div className="App">
      <DayPicker
          mode="single"
          className="day-picker"
          startMonth={startMonth}
          defaultMonth={startMonth}
        />
    </div>
  );
}

```
sandbox link - https://codesandbox.io/p/sandbox/strange-benz-vsh96j

## Expected Behavior

The initial month in calendar updates if the state variable is updated

## Actual Behavior

The initial month displayed s the value set during state variable 

## Screenshots

![image](https://github.com/user-attachments/assets/00bc4233-b0cf-40ae-9bf5-d0d1eeaa138e)
![image](https://github.com/user-attachments/assets/16c8f809-1d52-4211-bdfe-dcd483633fe7)

**Comment by gpbl** [comment]
Hi there!

I had to revert the fix for this change as it caused other problems. I'm not sure if this is actually a bug: When changing `startMonth` or `endMonth`, what should happen to the currently selected days? Which month should display if the calendar has already been navigated?

A workaround is to [control the month](https://daypicker.dev/docs/navigation#onmonthchange) using the `onMonthChange` and `month` props.
