### ISSUE TITLE
awkward behavior when rendering months after toMonth

### ISSUE THREAD

**Issue by giladgray** [gpbl/react-day-picker#243]
![image](https://cloud.githubusercontent.com/assets/464822/21627014/b96c469c-d1c9-11e6-8132-afcb99379d26.png)

The example above is configured such that `fromMonth` is 20 years ago and `toMonth` is the end of this year. Explicitly selecting the last month for the left calendar causes the right calendar to show the _first_ month in the range instead of the _next_ month, as expected given the normal passage of time.

**Comment by giladgray** [comment]
This issue was originally reported at https://github.com/palantir/blueprint/issues/391 but I think the issue lies here, not in our wrapper component?

**Comment by gpbl** [comment]
Hi @giladgray! 

I believe the calendar behaves correctly - but the header saying "January 1997" is wrong. The calendar on the right is actually January *2018*, which is disabled because out of the given range.

Compare [January 1997](https://www.timeanddate.com/calendar/?year=1997) with  [January 2018](https://www.timeanddate.com/calendar/?year=2018), as you see the 1997 doesn't have the 1st as Monday.

**Comment by giladgray** [comment]
_oh snap_ the issue must lie in our custom caption component then 😱  
thanks @gpbl!
