### ISSUE TITLE
With multiple calendars, navigation actions skip 'numberOfMonths'

### ISSUE THREAD

**Issue by anton-kabysh** [gpbl/react-day-picker#37]
For example, if `numberOfMonths=2`, and `initialMonth` is 'June'. Navigating through calendar with next/prev month show only pair of mounts `['June', 'July']`, `['August', 'Sept']`, `['Oct', 'Nov']` and etc. But not `['July', 'Aug']` or `['May', 'June']`.

Try navigation at http://www.gpbl.org/react-day-picker/ Range of days example.

**Comment by gpbl** [comment]
@anton-kabysh yeah thanks there was a reason for this, but I don't remember why :0

**Comment by gpbl** [comment]
I guess I intended the arrows as a way to change the whole view, so you should effectively jumping between months as specified in `numberOfMonths`. I'm trying the behavior you are suggesting and I agree it seems more consistent. However, when using the arrow keys to navigate between the days, it should add 2 months instead of one.
