### ISSUE TITLE
Clicking days on a calendar with multiple months makes it jump forward

### ISSUE THREAD

**Issue by gpbl** [gpbl/react-day-picker#38]
For example, in the [Range of days example](http://www.gpbl.org/react-day-picker/#examples/Range%20of%20days) when clicking on a day on the right month, it makes it jump to the next month.

**Comment by gpbl** [comment]
The reason for this behavior is [the code](https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L377-L379) added to navigate the calendar when clicking on outside days. The month should change instead only if the day has the `outside` modifier, *and* if it does not appear in the calendar.

**Comment by HNBowen** [comment]
@gpbl I'm still seeing this issue in the example and in my own implementation. I'm using v 7.2.4 of the library.

**Comment by gpbl** [comment]
@HNBowen which example? Here it works: https://codesandbox.io/s/x9rpwqrlz4?module=/example

**Comment by HNBowen** [comment]
@gpbl Sorry, I actually meant the Day Picker Input example. My bad! You can see the behavior I'm talking about in the 'Works with input fields' example on the react-day-picker.js.org home page. Clicking on the second month in the 'Range of days' calendar advances the calendar to the next month.

I think it may be this line? https://github.com/gpbl/react-day-picker/blob/39ad48ecadb18355e28ee5ef1741ca484949760d/src/DayPickerInput.js#L500

Clicking on a valid day resets the month of the overlay to the month of the day clicked, which I believe advances the calendar and causes the jump. Is this by design? Any advice for stopping the calendar from jumping ahead?

**Comment by gpbl** [comment]
@HNBowen oh I see. It looks like the `fromMonth` prop in `dayPickerProps` is ignored. Would you open another issue? And maybe investigate this? 🙏🏽

https://github.com/gpbl/react-day-picker/blob/2e936239ba2d9ada55eb3f76e3b4f582638bcddc/docs/src/code-samples/examples/input-from-to.js#L66-L72

**Comment by HNBowen** [comment]
@gpbl You got it!
