### ISSUE TITLE
Dev mode local sandbox

### ISSUE THREAD

**Issue by epsi10n** [gpbl/react-day-picker#559]
Do you provide any project level (source built-in) for more convinient development. How should I debug it if I want modify sources for my purposes.

**Comment by gpbl** [comment]
I need this as well 😄 

The idea is using the [docs website](https://github.com/gpbl/react-day-picker/tree/master/docs) to run the examples directly from source on localhost: i.e. on `NODE_ENV=development`, `import "react-day-picker"` should point to the [src](https://github.com/gpbl/react-day-picker/tree/master/src) directory. I've not yet explored how we could do this, but I believe [a custom webpack config](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/add-custom-webpack-config.md) should work.

**Comment by gpbl** [comment]
Just found that it is easier than I thought: run the [website](https://github.com/gpbl/react-day-picker/tree/master/docs) and instead of importing from `react-day-picker`, import from the source.

For example to test the [basic example](https://github.com/gpbl/react-day-picker/blob/master/docs/src/code-samples/examples/basic.js#L3) using the source:

```diff
// docs/src/code-samples/examples/basic.js
- import DayPicker from 'react-day-picker';
+ import DayPicker from '../../../../src/DayPicker';
```

**Comment by gpbl** [comment]
Even better, I've updated the gatsby config to import from src.  No need to import from `../../../` :)
 
Check out [CONTRIBUTING.md](https://github.com/gpbl/react-day-picker/blob/master/CONTRIBUTING.md#use-the-website-to-manually-test-changes)

**Comment by epsi10n** [comment]
thanks a lot
