### ISSUE TITLE
Add support of react-v0.14-rc1

### ISSUE THREAD

**Issue by istarkov** [gpbl/react-day-picker#61]
Add support of react-v0.14-rc1

**Comment by gregory90** [comment]
+1

**Comment by gpbl** [comment]
It is coming! It seems just the peer dependency in package.json. Let me test it out first.

**Comment by istarkov** [comment]
I've test it in internal project with 0.14rc, works fine.

**Comment by gpbl** [comment]
Thanks for the info! React 0.14 is breaking my tests because of [this](https://github.com/facebook/react/commit/e704503dc78476076c9f12e5147f26b0725c1e35#commitcomment-13362637). Also the example website doesn't work since react-tap-event-plugin does not support 0.14 [yet](https://github.com/zilverline/react-tap-event-plugin/issues/34). I'm tracking the changes in https://github.com/gpbl/react-day-picker/pull/62.

**Comment by gpbl** [comment]
Tracking the test issue here: https://github.com/facebook/react/issues/4952. The tap-event plugins is being updated as well 🎉

**Comment by gpbl** [comment]
Published as 1.0.7 🎉
