### ISSUE TITLE
Cannot read property 'focus' of undefined in DayPicker

### ISSUE THREAD

**Issue by speicus** [gpbl/react-day-picker#630]
Steps to reproduce:

1. Open https://codesandbox.io/s/23vz0vrn7r
2. DayPicker will display December, 2018
3. Click on January 5, 2019 (with is also displayed because of showOutsideDays is true).
4. Press left cursor key.

Result: An arrow is thrown: "Cannot read property 'focus' of undefined"
Expected result: the focus moves from January 5 to January 4.

![daypicker-focus](https://user-images.githubusercontent.com/443346/36540528-bf4826f8-17eb-11e8-9d85-72cda829758a.gif)

**Comment by gpbl** [comment]
Thanks for the report!

**Comment by gpbl** [comment]
So this is a special case when the "outside" day falls out of the `toMonth`/`fromMonth` months. I'm thinking maybe we should just hide the day (i.e. not displaying it at all)?

**Comment by gpbl** [comment]
This would be the result:

<img width="254" alt="screen shot 2018-02-25 at 10 16 25" src="https://user-images.githubusercontent.com/120693/36639833-fc5ea99c-1a14-11e8-8e86-845c3ce17e15.png">

**Comment by lohmatiy-lapa** [comment]
This behaviour can be reproduced without fromMonth/toMonth options. toMonth option is used in the example only to easily reproduce focus on the outside day. But outside day may got focus also by mouse button down event on day, then move mouse outside the day-picker component to any area without focus holding the button and then release the mouse button. But this is hard to describe, so in the example used toMonth to prevent month change to be able focus on day just by click event on it. There is gif with reproduce without using toMonth:
![focus_issue](https://user-images.githubusercontent.com/2681111/36658859-6cbe4854-1ae3-11e8-8807-bf4b6b40a533.gif)

By the way the same error could be reproduced for outside day before current month also by focus on it and press left cursor button:
![focus_issue_before_month](https://user-images.githubusercontent.com/2681111/36659001-0019cb0a-1ae4-11e8-9f15-a3a44cc597f4.gif)

Also there is strange behaviour when focusing outside day after month and then pressing right cursor button:
![focus_issue_after_month_right_button](https://user-images.githubusercontent.com/2681111/36659131-779ae506-1ae4-11e8-9cc1-94b67c40aba8.gif)

So the real reason of the issue is still exists. And also I think that hiding outside days in the border cases is not clear solution.

**Comment by speicus** [comment]
Basically, what @lohmatiy-lapa said. The issue is still there, and from what I understand, can be fixed by modifying this line: https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L305

There's actually a lot of places in `DayPicker.js` where `dayNodes` is accessed by index without checking if that index exists. @gpbl, please consider reopening this — I believe this can be easily fixed by adding additional checks.

**Comment by speicus** [comment]
As to hiding the days which fall out from `toMonth` / `fromMonth` — I think it’s a great idea.

**Comment by gpbl** [comment]
Published as [v7.1.0](https://www.npmjs.com/package/react-day-picker).
