### ISSUE TITLE
Remove default exports

### ISSUE THREAD

**Issue by TrySound** [gpbl/react-day-picker#638]
Default exports was added to spec to make simple interop with commonjs and similar module systems. But for now they introduce even more mess, especially with commonjs. So I suggest just to remove them everywhere.

Without default exports this can be achieved easily
```js
import { DayPicker, DateUtils, LocaleUtils, ModifiersUtils  } from 'react-day-picker';
```
or
```js
const { DayPicker, DateUtils, LocaleUtils, ModifiersUtils  } = require('react-day-picker');
```

**Comment by gpbl** [comment]
This is a good idea. Maybe it will help for typescript as well (asking @adidahiya)?

**Comment by adidahiya** [comment]
What mess do they introduce with commonjs? This seems like an unnecessary breaking change. There are plenty of JS library that still use default exports.

**Comment by TrySound** [comment]
this https://github.com/gpbl/react-day-picker/blob/master/DayPicker.dist.js
and this https://github.com/gpbl/react-day-picker/blob/master/src/index.js
and this https://github.com/gpbl/react-day-picker/blob/master/src/DayPicker.js#L573-L575

[Here's my thought about them](https://twitter.com/IAmTrySound/status/956983264304074752)

**Comment by adidahiya** [comment]
@TrySound I actually do agree with you in general about default exports (that's why I've promoted the [no-default-export TSLint rule](https://palantir.github.io/tslint/rules/no-default-export/)), but I don't think that's the prevailing consensus in the JS community right now and it would feel like unnecessary code churn in this project. Maybe it could eventually be bundled together with a bunch of other breaking changes, but I don't think @gpbl should treat this as an urgent priority.

**Comment by TrySound** [comment]
@adidahiya Of course this is a case only for major release. And I think it would be better to simplify stuff in the nearest major, not any further.

**Comment by lindskogen** [comment]
Yes, please go ahead with this! Typescript support is broken for now because of this.

Is there anyone working on this at the moment or would you accept a pull request?

**Comment by gpbl** [comment]
This will is already implemented in the upcoming mayor version, closing.
