### ISSUE TITLE
DayPickerInput onBlur always fires

### ISSUE THREAD

**Issue by Ronny25** [gpbl/react-day-picker#672]
**Version** 7.1.4

I'm using custom input component and custom overlay (modal component to be sure) to display your dayPicker. There are situations when an overlay is hiding after several clicks in modal outside dayPicker itself.

**Code**
I think the issue is here. It changes overlay state in onBlur method and I cannot affect on this behavior. Seems nice to have a prop for this because I want to fully control overlay show/hide actions.

```js
handleInputBlur(e) {
    this.setState({
      showOverlay:
        this.overlayNode && this.overlayNode.contains(e.relatedTarget),
    });
    if (this.props.inputProps.onBlur) {
      e.persist();
      this.props.inputProps.onBlur(e);
    }
  }
```

**Comment by gpbl** [comment]
We can add a new prop `hideOnInputBlur` that defaults to `true`. This should fix your issue @Ronny25 what do you think?

```jsx
if (this.props.hideOnInputBlur) {
  this.setState({   showOverlay:
    this.overlayNode && this.overlayNode.contains(e.relatedTarget),
  });
}
```

**Comment by Ronny25** [comment]
I think that might be a good problem solving. :clap: Thanks.

**Comment by gpbl** [comment]
@Ronny25 This issue is labelled as `good first issue` because I hope someone will take care of it.

**Comment by gpbl** [comment]
@Ronny25 I've looked this again but I don't understand where is your issue. With the last release v7.1.8 we have changed how the blur with the input field works. it would be nice to have [a codesandbox](https://codesandbox.io/s/XDAE3x0W8) to reproduce it, i.e. showing how it works now and what is your expected behaviour. 

Thanks! I will reopen this once I have more actionable informations.
