### ISSUE TITLE
 Compatible with IE8~IE11

### ISSUE THREAD

**Issue by buildacode** [gpbl/react-day-picker#684]
I found that the current plugin is not compatible with ie8-ie11
When will it be compatible with IE8~IE11?  ~*_*~

**Comment by gpbl** [comment]
Which plugin?

**Comment by PawelTroka** [comment]
@gpbl I think that @buildacode by plugin meant `react-day-picker`. Is it true that it's not compatible with IE8 - IE11 ?

**Comment by moag1000** [comment]
@gpbl DayPickerInput has issues since one of the last builds. You can't switch between months or pick dates in the calender. Every click on the calendar closes it and does NOT put a date into the underlying input field in at least IE 11

I did not have issues in the react-day-picker version that I downloaded from here in january.

**Comment by gpbl** [comment]
Oh yes this is a dup #668. @smesgr opened a PR that should fix it: #691, going to check it ASAP!
