### ISSUE TITLE
Cannot default the dayPickerInput to todays date

### ISSUE THREAD

**Issue by jlsorak** [gpbl/react-day-picker#714]
You cannot default the dayPickerInput to today's date. I want the datePickerInput to be defaulted to today's date so if the user wants today's date, they don't even have to interact with the calendar to use it. 

I thought a possible solution to this would be to set the `value` initially to today's date, however, the component does not `format` the `value` when inputted and therefore the date picker displays the date in MM/DD/YYYY, instead of DD/MM/YYYY as required. Codepen example of this attempted solution: https://codesandbox.io/s/w0qjj7oz97

**Comment by gpbl** [comment]
I think I understand what do you mean. You were expecting to write:

```js
value={new Date()}
```

instead you need to write

```js
value={formatDate(new Date())}
```

as in the sandbox above. Correct?

**Comment by jlsorak** [comment]
No, `value={formatDate(new Date())}` doesn't work as expected. In the codepen when I set the value like this it parses it in MM/DD/YYYY format instead of the desired DD/MM/YYYY format. E.g. it displays today's date (06 May 2018) as 05 June 2018: 
<img width="295" alt="screen shot 2018-05-06 at 15 32 39 1" src="https://user-images.githubusercontent.com/25332734/39674383-fa1e738c-5142-11e8-85e0-4c7c65e532e5.png">

**Comment by gpbl** [comment]
It works this way because you are not saying to `formatDate` how to format the date (see [source](https://github.com/gpbl/react-day-picker/blob/master/src/addons/MomentLocaleUtils.js#L49)):

However you don't need to pass the formatted date to `value` as it accepts a String or a Date: http://localhost:8000/api/DayPickerInput#value

See this example: 
https://codesandbox.io/s/7lzn7y2x1

Hope it helps!
