### ISSUE TITLE
Disabled DayPickerInput?

### ISSUE THREAD

**Issue by michaelgriffithus** [gpbl/react-day-picker#756]
Is there a way to disable the input on DayPickerInput? I have a scenario where I have to chose a begin and start date and sometimes the start date is fixed and should not be changed.  I would like to see the option to not be able to change the input but show the calendar.

**Comment by gpbl** [comment]
Have you tried to set it to readOnly? It should work!

**Comment by tomalexhughes** [comment]
Not sure if I'm missing something here, I'm passing a readOnly prop set to true but nothing seems to happen to the input?

```
        <DayPickerInput
          ...
          readOnly={true}
        />
```

Where am I going wrong?

**Comment by gpbl** [comment]
@tomalexhughes:

```jsx
<DayPickerInput inputProps={{ readOnly: true }} />
```

**Comment by gpbl** [comment]
To be clear: `disabled` will prevent from opening the overlay, `readOnly` will just make the input field read-only (but the overlay will open):

https://codesandbox.io/s/7yymmyokoj

**Comment by estenp** [comment]
> To be clear: `disabled` will prevent from opening the overlay, `readOnly` will just make the input field read-only (but the overlay will open):
> 
> https://codesandbox.io/s/7yymmyokoj

That seems like a bug, as you can still work around the "read" access to the input by "writing" via the picker. I'm trying to disallow someone from updating the value of the input via `readonly`, rather than `disabled`, as I still want readonly things, like focus/form submission. Is there a way to manually turn off the overlay via the component's API?

**Comment by mohaimenkhalid** [comment]
<DayPickerInput
      inputProps={{ disabled: true}}
   />
