### ISSUE TITLE
Question: How to Override `onDayClick` Hours?

### ISSUE THREAD

**Issue by wkentdag** [gpbl/react-day-picker#809]
I ran into an issue today when using `onDayClick` event to trigger an API call: the date that's returned from `onDayClick` always has its `hours` set to `12`, and after scanning the docs I don't see any way to override this behavior. 

You can see it replicated [here](https://codesandbox.io/s/j478xn2z6v) if you open the console and select a random date, note that the time is always noon.

It's easy enough to wrap `DayPicker` in another component, intercept `onDayClick` and edit the date before returning (see below), but I'd love it if I could pass a prop to `DayPicker` instead. Happy to submit a PR for this!

```js
onDayClick = (date) => {
  const d = date;
  d.setHours(0);
  this.props.onDayClick(d);
}
```

**Comment by raRaRa** [comment]
I ran into the same issue. Is there any specific reason why the hours is set to 12, instead of 0?

**Comment by gpbl** [comment]
It is set to noon for avoiding timezone issues. Not sure if we can fix them differently, but I’m open for suggestions :)

**Comment by jgonera** [comment]
For me ideally `DayPicker` would accept an optional [IANA `timeZone`](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) prop:

```tsx
<DayPicker timeZone="Europe/Warsaw" />
<DayPicker timeZone="UTC" />
<DayPicker />
```

Internally it could use [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) (so that we don't have to bloat this package with timeZone information) to convert returned dates to the right "start of day" (code not tested):

```ts
function dateParts(date: Date, timeZone: string): DateParts {
  return new Intl.DateTimeFormat('en-US', {
    hour12: false,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    timeZone,
  })
    .formatToParts(date)
    .reduce(
      (acc, { type, value }) => ({ ...acc, [type]: value }),
      {} as DateParts,
    );
}

function shiftDateToTimeZone(date: Date, timeZone: string): Date {
  const { year, month, day, hour, minute, second } = dateParts(date, timeZone);
  const datePart = [year, month, day].join('-');
  const timePart = [hour, minute, second].join(':');

  return new Date(`${datePart}T${timePart}`);
}

function getDateInTimeZone(
  year: number,
  monthIndex: number,
  day: number,
  timeZone: string,
): Date {
  const date = new Date(year, monthIndex, day);
  const diff = date.getTime() - shiftDateToTimeZone(date, timeZone).getTime();
  return new Date(date.getTime() + diff);
}
```

The values for choosing April 17, 2020 in the three `DayPicker`s above would be:
```
2020-04-16T22:00:00Z
2020-04-17T00:00:00Z
2020-04-17T07:00:00Z # Assuming default time zone, for me PDT
```

The disadvantage here is that `formatToParts` is not supported in any version of IE so it would work only in modern browsers. I suppose there could be some peer dependency that could be used to polyfill for IE.
