### ISSUE TITLE
TypeScript types are incomplete and should maybe be moved to DefinitelyTyped

### ISSUE THREAD

**Issue by ArcticZeroo** [gpbl/react-day-picker#849]
TypeScript types are pretty incomplete, e.g. DayPickerInput is missing a large handful of parameters. This makes TypeScript obviously fail to compile since it's literally missing parameters.

There's no reason that the types should be in this repo (as far as I know), generally typescript types (especially for modules that are not natively TS) are supposed to be in `@types/DefinitelyTyped` so that we can choose to install them. Right now I cannot build my project using `react-day-picker` which is problematic.

You could probably argue 'just add a PR to add the missing props' but it still doesn't make sense to force the types on people, especially because it wasn't maintained at least once which leads me to assume it may get that way again.

**Comment by ArcticZeroo** [comment]
It looks like in particular, `format` was being required but didn't actually seem to contribute at all to the day picker working. Adding it allows it to compile again

**Comment by davidspiess** [comment]
There are many issues right now with the types available in this repository and since the author doesn't wrote them himself, i support the idea of moving them to `DefinitelyTyped`.

**Comment by ArcticZeroo** [comment]
Yep, I don't have any personal experience with writing types for DefinitelyTyped but if the author is up for it I can look into it. 

It seems that, as a temporary fix, you can add `"skipLibCheck": true` to your tsconfig.json compiler options, and errors will be swallowed for anything in node_modules

**Comment by johnjesse** [comment]
I'm curious... why should they be moved to `DefinitelyTyped`? There are many projects that are not written in typescript and maintain their own typings. I would have thought that preferable so that the maintainers can update the typings as they are updating the library. Is it purely a maintenance issue?

**Comment by ArcticZeroo** [comment]
@johnjesse In a repo not written in typescript, where the maintainers do not actively maintain typings, moving it to DefinitelyTyped makes the typings optional (and they can be easily replaced by a local declarations file), whereas putting it into the module makes it so that a potentially outdated definition throws typescript errors or is missing information :(

**Comment by ZakTax** [comment]
I just came here to report that ts complains when I try to import `DateUtils` since the typescript defs don't include the `utils` file. I would also appreciate better TS defs

**Comment by gpbl** [comment]
Type definitions were on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), but we run in the opposite issue: they weren’t in sync with the latest releases. We decided anyway to move the definitions to this repo – which I think it is fine, because they don’t require much extra work.

However, @ArcticZeroo is right observing that type definitions here are not a first-class citizen. I usually trust what the TS developers send as PR, and merge the fixes as soon as possible.

(I’m considering to rewrite this project in TypeScript, BTW)

**Comment by joshbedo** [comment]
This is such a pain in the ass to use currently without type definitions just throwing that out there. It throws a ton of errors with the examples where you have to define things yourself. Spent an extra hour working around errors with DayPickerInput.
