### ISSUE TITLE
The value of the input field can not clear

### ISSUE THREAD

**Issue by TakanoriMizuta** [gpbl/react-day-picker#955]
**Describe the bug**
Once set the date into input field,
input field value can NOT clear even when value prop set to "".

**To Reproduce**
https://codesandbox.io/s/7m6q1y8xmj (This sample is NOT mine, thanks gpbl!)

1. Select some date
1. Click 'Reset' button

**Expected behavior**
After clicking Reset button ,Input field makes clear.

**Screenshots**

* Ver 7.4.0
![daypicker740](https://user-images.githubusercontent.com/54613890/68917937-a826ae80-07af-11ea-9835-03d3c75ab338.gif)
* Ver 7.3.2
![daypicker732](https://user-images.githubusercontent.com/54613890/68917935-a52bbe00-07af-11ea-8bac-c20dd56f4892.gif)

**Additional context**
This issue does not occur in Ver7.3.2, only occurs in ver 7.4.0

**Comment by seowalex** [comment]
For anyone else interested, the bug seems to have been introduced in commit 81ac11675d6db9a21a42dde55cda5751eb483ba0, when `value={this.state.typedValue || this.state.value}` was changed to `value={this.state.value || this.state.typedValue}`. Reverting this change seems to have solved the problem for me.
