### ISSUE TITLE
Caption.js:10 Uncaught TypeError: f.default.instanceOf is not a function     at Object.<anonymous> (Caption.js:10)

### ISSUE THREAD

**Issue by andrew4kariuki** [gpbl/react-day-picker#975]
Caption.js:10 Uncaught TypeError: f.default.instanceOf is not a function
    at Object.<anonymous> (Caption.js:10)

**Comment by KyorCode** [comment]
A bit more information would be required to actually be able to help you here.

**Comment by KyorCode** [comment]
Could it be you have no reference towards the prop-types library? I assume you are using a < V8 version.

**Comment by sowdri** [comment]
This issue is happening if the library is loaded from `unpkg`

`<script src="https://unpkg.com/react-day-picker@7.4.0/lib/daypicker.min.js"></script>`

Refer to the attached screenshot for more info: 

![image](https://user-images.githubusercontent.com/3541310/75320477-ae541d00-58be-11ea-9872-a56a817fa0eb.png)

**Comment by gpbl** [comment]
This should be fixed now - please upgrade.
